//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by smc.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_SMCTYPE                     129
#define IDS_COMMON_PARAMS_CAPTION       129
#define IDS_SUBST_PARAMS_CAPTION        130
#define IDD_SETSCROLL_SIZE              131
#define IDS_PROFILE_PARAMS_CAPTION      131
#define IDS_LOG_PARAMS_CAPTION          132
#define IDD_HOTKEYS                     133
#define IDS_SCRIPT_PAGE__CAPTION        133
#define IDD_SET_NAME                    134
#define IDS_ALIAS_PAGE_CAPTION          134
#define IDS_GROUPS_PAGE_CAPTION         135
#define IDS_ACTION_PAGE_CAPTION         136
#define IDD_NEW_HOTKEY                  137
#define IDS_HLIGHT_PAGE_CAPTION         137
#define IDS_HKEY_PAGE_CAPTION           138
#define IDD_COLORS_DLG                  139
#define IDS_SUBST_PAGE_CAPTION          139
#define IDS_SCRIPTFILES_PAGE_CAPTION    140
#define IDD_PARAMS_PAGE                 141
#define IDD_SUBST_PAGE                  142
#define IDD_NEW_PROFILE                 143
#define IDD_PROFILE_PAGE                144
#define IDD_PROFILE_LIST                145
#define IDC_CURSOR1                     147
#define IDD_ANSI_COLOR                  148
#define IDD_LOG_PARAMS_PAGE             149
#define IDD_SCRIPT_PAGE                 150
#define IDD_SCRIPT_PARSE                151
#define IDD_KEYWORDS_DLG                153
#define IDD_JMC_ALIAS                   154
#define IDD_JMC_GROUPS                  155
#define IDB_CONNECTED                   157
#define IDB_LOGGED                      159
#define IDB_MARKED                      160
#define IDD_ADD_GROUP                   161
#define IDB_GROUP_ICONS                 162
#define IDD_JMC_ACTIONS                 162
#define IDD_JMC_HLIGHT                  163
#define IDD_JMC_HOTKEY                  164
#define IDD_TESTTEXT                    169
#define IDD_JMC_SUBST                   173
#define IDD_SCRIPT_FILES                174
#define IDD_JMC_SCRIPTFILES             175
#define IDD_EDIT_BAR                    176
#define ID_DRAW_TEXT_ADDED              400
#define ID_OUTPUT_TEXT_ADDED            401
#define ID_INDICATOR_LOGGED             500
#define ID_INDICATOR_CONNECTED          501
#define ID_PATH_WRITING                 502
#define ID_TICKER                       503
#define ID_INDICATOR_INFO1              504
#define ID_INDICATOR_INFO2              505
#define ID_INDICATOR_INFO3              506
#define ID_INDICATOR_INFO4              507
#define ID_INDICATOR_INFO5              508
#define IDC_EDIT                        1000
#define IDC_COUNT                       1001
#define IDC_SETS                        1002
#define IDC_ACTION                      1004
#define IDC_REM_SET                     1005
#define IDC_ADD_SET                     1006
#define IDC_REM_KEY                     1007
#define IDC_ADD_KEY                     1008
#define IDC_COPY_SET                    1009
#define IDC_NAME                        1010
#define IDC_KEYS                        1013
#define IDC_HOTKEY                      1014
#define IDC_SET_KEY                     1015
#define IDC_KEY                         1016
#define IDC_FORE_COLOR                  1018
#define IDC_BACK_COLOR                  1019
#define IDC_START_LINE                  1021
#define IDC_END_LINE                    1022
#define IDC_MIN_LEN                     1023
#define IDC_ONE_COPY                    1024
#define IDC_ALLOW_SUBST                 1025
#define IDC_SUBST_LIST                  1026
#define IDC_OLD                         1027
#define IDC_NEW                         1028
#define IDC_ADD                         1029
#define IDC_REMOVE                      1030
#define IDC_COMMAND_CHAR                1032
#define IDC_COMMAND_DELIMITER           1033
#define IDC_START_FILE                  1035
#define IDC_SAVE_FILE                   1036
#define IDC_COMMAND                     1037
#define IDC_LIST                        1038
#define IDC_HISTORY_SIZE                1039
#define IDC_KEEP_ANSI_IN_LOG            1040
#define IDC_RMA_SUPPORT                 1041
#define IDC_APPEND_LOG_MODE             1042
#define IDC_OVERWRITE_LOG_MODE          1043
#define IDC_DARK_ONLY                   1043
#define IDC_DISPLAY_INPUT               1044
#define IDC_PRODUCT_NAME                1045
#define IDC_VERTION                     1046
#define IDC_DISPLAY_COMMANDS            1046
#define IDC_COPYRIGHT                   1047
#define IDC_EMAIL                       1048
#define IDC_WWW                         1049
#define IDC_WWW1                        1050
#define IDC_CLEAR_INPUT                 1051
#define IDC_CONNECT_BEEP                1052
#define IDC_AUTO_RECONNECT              1053
#define IDC_LANG                        1054
#define IDC_TEXT                        1055
#define IDC_SPLIT_ONBACKSCROLL          1056
#define IDC_PREV                        1057
#define IDC_NEXT                        1058
#define IDC_HTML_LOG                    1059
#define IDC_ALLOW_DEBUG                 1061
#define IDC_SEND_SINGLE                 1062
#define IDC_SEND_DOWBLE                 1063
#define IDC_ERROR_MSGBOX                1063
#define IDC_RECIVE_SINGLE               1064
#define IDC_ERROR_WINDOW                1064
#define IDC_GROUPS                      1064
#define IDC_RECIVE_DOWBLE               1065
#define IDC_ALIAS                       1065
#define IDC_ERROR_OUTPUT                1066
#define IDC_GRP                         1068
#define IDC_ENABLED                     1072
#define IDC_GLOBAL                      1073
#define IDC_PRIORITY                    1076
#define IDC_ACTIONS                     1077
#define IDC_SEND                        1083
#define IDC_SEND_LINE                   1084
#define IDC_TRIG_DELAY                  1085
#define IDC_UP                          1090
#define IDC_DOWN                        1091
#define IDC_COMMONLIB                   1095
#define IDC_PROFILESCRIPT               1096
#define IDC_TOKEN_INPUT                 1103
#define IDC_RESTORE_DEFAULT             1104
#define IDC_TOKEN_LAST                  1105
#define IDC_AUTO_END                    1106
#define IDC_LANG_FILE                   1107
#define IDC_WWW2                        1107
#define IDC_LANG_SECT                   1108
#define ID_OPTIONS_SCROLLBUFFER         32771
#define ID_OPTIONS_FONT                 32772
#define ID_OPTIONS_HOTKEYS              32774
#define ID_OPTIONS_COLORS               32776
#define ID_OPTIONS_OPTIONS              32777
#define ID_PAUSE                        32778
#define ID_FILE_LOADPROFILE             32779
#define ID_FILE_SAVEPROFILE             32780
#define ID_FILE_SAVEPROFILEAS           32781
#define ID_FILE_NEW_PROFILE             32782
#define ID_HELP_CONTENTS                32784
#define ID_UNSPLIT                      32786
#define ID_SCRIPTING_RELOADSCRIPT       32787
#define ID_SCRIPTING_ADDSCRIPTLET       32788
#define ID_VIEW_OUTPUTWINDOW            32789
#define ID_SCRIPTING_BREAK              32790
#define ID_OPTIONS_KEYWORDS             32791
#define ID_SCRIPTING_LUNCHDEBUGER       32792
#define ID_EDIT_JMCOBJECTS              32793
#define ID_VIEW_MUDEMULATOR             32795
#define ID_SHOW_OUTPUT                  32798
#define ID_VIEW_OUTPUTWINDOW1           32800
#define ID_VIEW_OUTPUTWINDOW2           32801
#define ID_VIEW_OUTPUTWINDOW3           32802
#define ID_VIEW_OUTPUTWINDOW4           32803
#define ID_VIEW_OUTPUTWINDOW5           32804
#define ID_VIEW_OUTPUTWINDOW6           32805
#define ID_VIEW_OUTPUTWINDOW7           32806
#define ID_VIEW_OUTPUTWINDOW8           32807
#define ID_VIEW_OUTPUTWINDOW9           32808
#define IDS_AP_ALIAS_COL                61204
#define IDS_AP_GROUP_COL                61205
#define IDS_AP_TEXT_COL                 61206
#define IDS_AP_ERR_EXISTS               61207
#define IDS_SP_ERR_MAX                  61208
#define IDS_SP_ERROR                    61209
#define IDS_SP_ERR_EXIST                61210
#define IDS_ALL_GROUPS                  61211
#define IDS_TP_PATTERN_COL              61212
#define IDS_TP_COMMAND_COL              61213
#define IDS_TP_PRIORITY_COL             61214
#define IDS_GP_DEL_QUES                 61215
#define IDS_GP_ENABLED_COL              61216
#define IDS_GP_NAME_COL                 61217
#define IDS_GP_ERR_EMPTY                61218
#define IDS_GP_ERR_EXIST                61219
#define IDS_HP_ERR_EXIST                61220
#define IDS_KP_KEY_COL                  61221
#define IDS_KP_NEW                      61222
#define IDS_CLOSE                       61223
#define IDS_OUTPUT                      61224
#define IDS_OPTIONS                     61225
#define IDS_JABA_TITLE                  61226
#define IDS_JMC_OBJECTS                 61227
#define IDS_ERR_DISCONNECT              61228
#define IDS_QUES_NEW_PROFILE            61229
#define IDS_PROFILE_SAVED               61230
#define IDS_SF_ALREADY_USED             61231
#define IDS_SF_ADD_CAPTION              61232
#define IDS_SF_ALREADY_USED_DEFAULT     61233

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
